# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 18:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('status', models.IntegerField(choices=[('Backlog', 1), ('Ready', 2), ('In Progress', 3), ('Complete', 4)], default=1)),
                ('priority', models.IntegerField(choices=[('High', 1), ('Moderate', 2), ('Low', 3)], default=2)),
                ('description', models.TextField(max_length=1250)),
            ],
        ),
    ]
