# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-12 20:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_task_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ('status', 'priority', 'created')},
        ),
        migrations.AddField(
            model_name='task',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 12, 20, 36, 29, 163982, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
